services:
  rawtcp-server:
    build: .
    volumes:
      - ./:/opt/app:ro
    working_dir: /opt/app
    command: php rawtcp/server.php

  rawtcp-clients:
    build: .
    command: php rawtcp/client.php
    volumes:
      - ./:/opt/app:ro
    working_dir: /opt/app
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
